### ISSUE TITLE
Не работает код из примера api.getUserInfo() (в iFrame)

### ISSUE THREAD

**Issue by ww33** [VKCOM/vk-mini-apps-api#11]
В файл main.ts (Vue js) поместил код из примера:

```
import { VKMiniAppAPI } from '@vkontakte/vk-mini-apps-api';
const api= new VKMiniAppAPI();
api.initApp();
api.getUserInfo()
	.then(userInfo => {
		console.log(userInfo);
	})
	.catch(e => console.log(e));
```

Выложил на Github Pages.
В настройках приложения в поле **Адрес IFrame** прописал "https://ww33.github.io/vue-chat/"

Приложение открывается, но в консоль ничего не выводится - ни then, ни catch.

**Comment by xpyctumo** [comment]
Привет. 
Нужен тип приложения **VK Mini Apps**, а не iframe. 

![E4632FD2-B548-444D-BA64-35FC18811694](https://user-images.githubusercontent.com/30053565/76142110-9bd6a200-607b-11ea-8af4-fed68767a8a3.jpeg)
