### ISSUE TITLE
Как получить auth_key с сервера ВКонтакте?

### ISSUE THREAD

**Issue by ww33** [VKCOM/vk-mini-apps-api#13]
Из документации:
auth_key вычисляется на сервере ВКонтакте следующим образом:
auth_key = md5(api_id + '_' + viewer_id + '_' + api_secret)

Как  получить auth_key с сервера VK в приложении? В параметрах url его нет, методов для его получения не видно...

**Comment by xpyctumo** [comment]
Привет. Для mini apps актуальна эта страница.

https://vk.com/dev/vk_apps_docs3?f=6.1%2B%D0%9F%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D1%8C%2B%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D0%BE%D0%B2%2B%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0
