### ISSUE TITLE
Как получить массив друзей?

### ISSUE THREAD

**Issue by ww33** [VKCOM/vk-mini-apps-api#14]
Метод getFriends вызывает интерактивный список.

JavaScript SDK имеет friends.get, но вроде как JavaScript SDK  поддерживается только до 1 мая 2020.

Как актуально получить список друзей (не интерактивный) для последующего анализа?

Спасибо.

**Comment by xpyctumo** [comment]
Пожалуйста, изучите документацию по [Mini Apps](https://vk.com/dev/vk_apps_docs).

[friends.get](https://vk.com/dev/friends.get) - метод API VK. Для его работы необходимо выполнить следующие шаги.

1. Для начала получить [токен](https://github.com/VKCOM/vk-mini-apps-api/blob/master/docs/classes/vkminiappapi.md#--getfriends).

```js
api.getAccessToken(appId, "friends");
```

2. Затем, вызвать метод [API](https://github.com/VKCOM/vk-mini-apps-api/blob/master/docs/classes/vkminiappapi.md#callapimethod).

```js
api.callAPIMethod("friends.get", {"access_token": "YOUR_TOKEN_HERE", "v": "5.100"});
```
