### ISSUE TITLE
How to use when running outside of VK platform?

### ISSUE THREAD

**Issue by reflash** [VKCOM/vk-mini-apps-api#16]
Hi!

I've faced an issue. I'm currently using the api to get user info. When I'm trying to run the same code outside of VK (just from my browser), it neither fails nor succeeds. It seems it is stuck in some constant loop because await is never finished and it doesn't throw anything either.
What should I do in that case?

**Comment by danakt** [comment]
You cannot use the package outside VK, because you need to interact with the interface and the VK environment

**Comment by reflash** [comment]
@danakt do I have to use some wrappers if I want to test app pages on my local machine? It's quite difficult for multiple developers to work on the same app. 
The only difficulty is that api calls do not throw any exceptions if I'm outside of VK, meaning I cannot catch and set some default values for testing.

**Comment by danakt** [comment]
Unfortunately, there are no wrappers for testing applications without VK environment yet. You can use tools like [ngrok](https://ngrok.com) to expose your local web server

**Comment by reflash** [comment]
> Unfortunately, there are no wrappers for testing applications without VK environment yet. You can use tools like [ngrok](https://ngrok.com) to expose your local web server

Thanks, but it still will require to create an app for each member of my team to work in parallel. I could technically mock the data if I would know I'm not in VK environment, but it seems the api methods are just not failing
