### ISSUE TITLE
Проблема с openCodeReader

### ISSUE THREAD

**Issue by Inumaru** [VKCOM/vk-mini-apps-api#7]
Resolve промиса что возвращает данная ф-ция не выполняется с @vkontakte/vk-connect но выполняется с @vkontakte/vk-connect-mock.
При этом само событие VKWebAppOpenCodeReaderResult из данных библиотек отрабатывает успешно.
Использую
@vkontakte/vk-connect 1.8.7
@vkontakte/vk-connect-mock 2.1.0
@vkontakte/vk-mini-apps-api 0.5.0

**Comment by xpyctumo** [comment]
Привет. 
Это проблема на клиентах (известно про __Android__), а не в библиотеке.
