### ISSUE TITLE
Не работает в браузерах после обновления vk connect на vk bridge

### ISSUE THREAD

**Issue by duceum** [VKCOM/vk-mini-apps-api#9]
Обновил пакет vk connect на vk bridge.

После этого библиотека vk-mini-apps-api перестала работать в браузерах, как в десктопных, так и на мобильных. В нативных клиентах работает корректно. Пример кода ( в самом приложении используется чуть другой, но этот тоже не работает)

```
import bridge from '@vkontakte/vk-bridge';
import { VKMiniAppAPI } from '@vkontakte/vk-mini-apps-api';

const api = new VKMiniAppAPI();
api.initApp();

api.getUserInfo()
  .then(userInfo => {
  			  console.log(userInfo);
			  console.log(userInfo.id);
  			  // в браузерах выводит undefined в обоих случаях
	   })
  .catch(function(err) {
    		console.log('Error :-S', err);
  	    });
```

Куда смотреть, куда копать чтобы заработало? Как понять в чем ошибка? смотрел запросы в серверу через инструменты разработчика в хром , запросы к серверу вк не идут, в общем списке не показываются.

package file:
```
"dependencies": {
    "@vkontakte/icons": "^1.17.1",
    "@vkontakte/mvk-mini-apps-scroll-helper": "^1.2.0",
    "@vkontakte/vk-bridge": "^2.0.7",
    "@vkontakte/vk-mini-apps-api": "^0.6.3",
    "@vkontakte/vkui": "^3.4.2",
    ...
```

**Comment by danakt** [comment]
Исправлено! Спасибо :)

**Comment by duceum** [comment]
После обновления все заработало, спасибо!
